[project]
name = "dnd-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2",
    "dotenv>=0.9.9",
    "honcho-ai>=1.4.0",
    "openai>=1.102.0",
    "py-cord>=2.6.1",
]
